import panoramaPanels from "@moddota/dota-data/files/panorama/panels";
import type { DeclarationsContextType } from "../components/api/Docs/DeclarationsContext";

// Panel types usable in layout XML, generated by the game's layout XSD dump.
// Each panel lists only the XML attributes it declares itself; attributes of
// the type it extends (and further up the chain) also apply to it.
export const panoramaPanelsScope: DeclarationsContextType = {
  root: "/panorama/panels",
  declarations: panoramaPanels
    .map((panel) => ({
      kind: "class" as const,
      name: panel.name,
      extend: panel.base,
      isStarred: false,
      members: panel.attributes.map((attr) => ({
        kind: "field" as const,
        name: attr.name,
        description: attr.description,
        types: ["string"],
      })),
    }))
    .sort((a, b) => a.name.localeCompare(b.name)),
};
